### ISSUE TITLE
setup fails on windows

### ISSUE THREAD

**Issue by jteiwes** [pyspace/pyspace#12]
The setup fails if run on windows since the os module does not have the "fchmod" function. The error comes from setup.py, line 399:

os.fchmod(shortcut_file.fileno(), 0775)

**Comment by MMKrell** [comment]
The line has to be removed for windows systems but kept for unix based systems. We will change that soon with the next release. It is required for unix systems to change the ownership of the main execution files from Python to the real user and make the file executable to enable the short commands "./launch.py" and "./performance_result_analysis.py".

**Comment by MMKrell** [comment]
It should be working now.
